version: '3.5'

networks:
  app-ngcash:
    driver: bridge

volumes:
  postgres:

services:
  postgres:
    container_name: postgres_container
    image: postgres
    networks:
      - app-ngcash
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: westeros
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: always
